name: REST API Testing

on:
    push:
        branches:
          - main
        paths:
          - 'spotify_m/src/api/artists.py'
          - 'spotify_m/src/api/playlists.py'
          - 'spotify_m/src/api/songs.py'
          - 'spotify_m/src/api/users.py'
          - 'spotify_m/src/test_myfunctions.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Test code
      run: pytest test_myfunctions.py
      working-directory: spotify_m/src
            
