name: Check Models.py Update

on:
  push:
    branches:
      - main
    paths:
      - spotify_m/src/models.py

jobs:
  check-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Debugging
      run: |
        git log --oneline
        cat spotify_m/src/models.py
        echo "Before Commit Hash: ${{ github.event.before }}"
        echo "After Commit Hash: ${{ github.sha }}"

    - name: Run Python Script
      run: |
        if [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'models.py')" ]; then
          echo "models.py has been updated."
          git diff ${{ github.event.before }} ${{ github.sha }} -- spotify_m/src/models.py > models_change.diff
        else
          echo "No update in models.py."
        fi